# .bandit.yaml - Bandit Security Scanner Configuration
# Personal Password Manager - Security Vulnerability Detection

# Exclude paths
exclude_dirs:
  - /tests/
  - /venv/
  - /.venv/
  - /build/
  - /dist/
  - /__pycache__/
  - /data/
  - /backups/
  - /.git/

# Tests to skip
skips:
  # B101: assert_used - We use asserts in tests
  - B101
  # B105: hardcoded_password_string - We have examples/tests
  - B105
  # B106: hardcoded_password_funcarg - We have examples/tests
  - B106
  # B603: subprocess_without_shell_equals_true - We need this for some operations
  - B603

# Tests to run (all others by default)
tests:
  - B201  # flask_debug_true
  - B301  # pickle
  - B302  # marshal
  - B303  # md5
  - B304  # insecure_cipher
  - B305  # insecure_cipher_mode
  - B306  # mktemp_q
  - B307  # eval
  - B308  # mark_safe
  - B310  # urllib_urlopen
  - B311  # random
  - B312  # telnetlib
  - B313  # xml_bad_cElementTree
  - B314  # xml_bad_ElementTree
  - B315  # xml_bad_expatreader
  - B316  # xml_bad_expatbuilder
  - B317  # xml_bad_sax
  - B318  # xml_bad_minidom
  - B319  # xml_bad_pulldom
  - B320  # xml_bad_etree
  - B321  # ftplib
  - B323  # unverified_context
  - B501  # request_with_no_cert_validation
  - B502  # ssl_with_bad_version
  - B503  # ssl_with_bad_defaults
  - B504  # ssl_with_no_version
  - B505  # weak_cryptographic_key
  - B506  # yaml_load
  - B507  # ssh_no_host_key_verification
  - B601  # paramiko_calls
  - B602  # subprocess_popen_with_shell_equals_true
  - B604  # any_other_function_with_shell_equals_true
  - B605  # start_process_with_a_shell
  - B606  # start_process_with_no_shell
  - B607  # start_process_with_partial_path
  # B608 removed - deprecated in newer Bandit versions
  - B609  # linux_commands_wildcard_injection
  - B610  # django_extra_used
  - B611  # django_rawsql_used
  - B701  # jinja2_autoescape_false
  - B702  # use_of_mako_templates
  - B703  # django_mark_safe

# Severity level (LOW, MEDIUM, HIGH)
level: MEDIUM

# Confidence level (LOW, MEDIUM, HIGH)
confidence: MEDIUM
